"use client";
import React,{useMemo,useState}from"react";
import{GoogleMap,LoadScript,Marker,InfoWindow}from"@react-google-maps/api";
import{Search,Store,MapPin,UserPlus,LayoutDashboard,Users,Ticket,Brain,Crown,Upload,Star,Navigation,ChevronDown,Wallet,CreditCard,CalendarDays,QrCode,Bell,Send,Vote,BarChart3,Lock,Sparkles}from"lucide-react";

const businessName=process.env.NEXT_PUBLIC_BUSINESS_NAME||"LMH Enterprise LLC";
const defaultCenter={lat:38.4221,lng:-77.4083};
const categories=[
{key:"family",label:"Family & BBQ",cost:950,zones:["Grill zone","Food line","Games","Kids area"],checks:["Fuel","Ice","Trash","Shade"]},
{key:"wedding",label:"Wedding",cost:5200,zones:["Ceremony","Reception","Dance floor","Photo area"],checks:["Flowers","Seating chart","DJ","Weather backup"]},
{key:"corporate",label:"Corporate",cost:3400,zones:["Registration","Main room","Breakouts","Catering"],checks:["Badges","Projector","Agenda","Wi-Fi"]},
{key:"music",label:"Music & Concert",cost:6500,zones:["Stage","Sound booth","Audience","Vendors"],checks:["Sound","Lights","Power","Security"]},
{key:"political",label:"Political & Civic",cost:4200,zones:["Podium","Media zone","VIP","Security"],checks:["Permits","Compliance","Media access","Crowd flow"]},
{key:"custom",label:"Custom Event",cost:1000,zones:["Main area","Guest flow","Vendor zone","Safety"],checks:["Goal","Budget","Vendors","Timeline"]}
];
const demoVendors=[
{name:"Elite Sound DJs",category:"DJ / Music",location:"Stafford, VA",price:"$350 - $900",rating:4.9,lat:38.4221,lng:-77.4083,verified:true},
{name:"Fresh Flame Catering",category:"Catering",location:"Fredericksburg, VA",price:"$15 - $45/guest",rating:4.8,lat:38.3032,lng:-77.4605,verified:true},
{name:"GlowPro Lighting",category:"Lighting / AV",location:"Washington, DC",price:"$300 - $1,500",rating:4.7,lat:38.9072,lng:-77.0369,verified:false},
{name:"Premier Event Rentals",category:"Tents / Tables",location:"Richmond, VA",price:"$500 - $2,500",rating:4.8,lat:37.5407,lng:-77.4360,verified:true},
{name:"CivicStage Productions",category:"Political / Civic",location:"Northern VA",price:"$1,500 - $7,500",rating:4.6,lat:38.8048,lng:-77.0469,verified:false},
{name:"Venue Luxe Hall",category:"Venue",location:"Stafford, VA",price:"$800 - $5,000",rating:4.9,lat:38.4331,lng:-77.4100,verified:true}
];
const guests=["Tanya","Tyronne","Joshua","James","Nicole","Calvin","Lori","Jonathan","Jason","Justin"].map((name,i)=>({name,email:"",rsvp:i<4?"Yes":"Pending",paid:i<3,ticket:`GG-${name.toUpperCase()}-${1000+i}`}));
function money(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
async function postJson(path,body){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return r.json()}
function Card({children}){return <div className="panel rounded-[1.75rem] p-5">{children}</div>}
function Field({label,value,set}){return <label><span className="text-xs text-stone-500">{label}</span><input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-2xl border border-stone-200 bg-white/70 px-4 py-3 outline-none"/></label>}
function Section({icon:Icon,title,text,children}){return <section><div className="mb-6"><div className="flex gap-3 items-center"><Icon className="text-stone-500"/><h2 className="text-4xl font-light">{title}</h2></div><p className="text-stone-500">{text}</p></div>{children}</section>}
function Metric({icon:Icon,label,value}){return <Card><div className="flex gap-3 items-center"><div className="orb-sm scale-75"/><div><p className="text-sm text-stone-500">{label}</p><p className="text-xl font-light">{value}</p></div></div></Card>}
function VendorGrid({vendors,setTab}){return <div className="grid md:grid-cols-3 gap-4">{vendors.map(v=><Card key={v.name}><div className="flex justify-between"><div><h4 className="text-xl font-light">{v.name}</h4><p className="text-stone-500">{v.category}</p></div><span className="flex gap-1 text-sm"><Star className="h-4 w-4"/>{v.rating||"New"}</span></div><p className="mt-4 text-sm text-stone-500"><MapPin className="inline h-4 w-4 mr-1"/>{v.location}</p><p className="mt-2">{v.price}</p>{v.verified&&<p className="text-xs text-emerald-700 mt-2">Verified vendor</p>}<button onClick={()=>setTab("vendors")} className="primary rounded-2xl px-4 py-3 mt-5 w-full">Book Vendor</button></Card>)}</div>}

export default function Page(){
const[tab,setTab]=useState("marketplace"),[cat,setCat]=useState("family"),[center,setCenter]=useState(defaultCenter),[selected,setSelected]=useState(null),[vendors,setVendors]=useState(demoVendors),[search,setSearch]=useState(""),[status,setStatus]=useState("Live vendor + map version ready."),[plan,setPlan]=useState("free"),[vendorForm,setVendorForm]=useState({name:"",category:"DJ / Music",location:"",price:"",email:""});
const active=categories.find(c=>c.key===cat)||categories[0];
const items=[{cost:1850},{cost:350},{cost:300},{cost:800},{cost:active.cost}];
const total=items.reduce((s,i)=>s+i.cost,0),paid=guests.filter(g=>g.paid).length,split=total/guests.length,collected=paid*split;
const tabs=[["marketplace",Store,"Marketplace"],["map",MapPin,"Live Map"],["join",UserPlus,"Vendor Join"],["dashboard",LayoutDashboard,"Dashboard"],["guests",Users,"Guests"],["vendors",Store,"Vendors"],["tickets",Ticket,"Tickets"],["ai",Brain,"AI"],["plans",Crown,"Plans"],["redeploy",Upload,"Redeploy"]];

async function call(path,body){try{const d=await postJson(path,body);setStatus(d.message||"Done.");return d}catch{setStatus("Request failed. Check keys and logs.");return{}}}
function getLocation(){navigator.geolocation?.getCurrentPosition(p=>{setCenter({lat:p.coords.latitude,lng:p.coords.longitude});setStatus("Location detected.");},()=>setStatus("Location unavailable."))}
async function searchLive(kind="event vendors"){const d=await call("/api/vendors/search-nearby",{query:kind,lat:center.lat,lng:center.lng});if(d.results?.length)setVendors(d.results)}
async function submitVendor(){const d=await call("/api/vendors/join",{vendor:vendorForm,businessName});setVendorForm({name:"",category:"DJ / Music",location:"",price:"",email:""})}
function chooseCategory(k){setCat(k);setTab("dashboard");setStatus(`${(categories.find(c=>c.key===k)||{}).label} layout loaded.`)}

return <main className="min-h-screen px-5 py-7"><div className="mx-auto max-w-7xl">
<header className="panel rounded-[2rem] p-5 md:p-6 mb-7 flex flex-wrap justify-between gap-5 items-center"><div className="flex items-center gap-4"><div className="orb-sm"/><div><h1 className="text-3xl md:text-4xl font-light tracking-[.08em] uppercase">GatherGenius</h1><p className="text-sm text-stone-500">Live vendor map + marketplace for {businessName}</p></div></div><div className="flex gap-3"><label className="relative"><select value={cat} onChange={e=>chooseCategory(e.target.value)} className="appearance-none rounded-full bg-white/75 border border-stone-200 px-5 py-3 pr-10 text-sm outline-none">{categories.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select><ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 h-4 w-4"/></label><div className="rounded-full bg-white/70 border border-stone-200 px-5 py-3 text-sm">{plan} plan</div></div></header>
<nav className="panel rounded-[2rem] p-2 flex flex-wrap gap-2 mb-8">{tabs.map(([k,Icon,label])=><button key={k} onClick={()=>setTab(k)} className={`rounded-[1.35rem] px-4 py-2 text-sm flex items-center gap-2 ${tab===k?"primary":"btn"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>

{tab==="marketplace"&&<Section icon={Store} title="Public Marketplace" text="Find vendors, venues, events, and services before login."><div className="grid lg:grid-cols-3 gap-6 mb-6"><div className="panel rounded-[2rem] p-8 lg:col-span-2"><div className="orb mb-8"/><h2 className="text-5xl font-light mb-4">Find everything your event needs.</h2><p className="text-stone-500 max-w-2xl mb-6">Search vendors, venues, hotels, DJs, lighting, catering, political/civic logistics, tickets, and AI-built event layouts.</p><div className="flex flex-col md:flex-row gap-3"><div className="flex-1 rounded-full bg-white/75 border border-stone-200 px-5 py-4 flex items-center gap-3"><Search className="h-5 w-5 text-stone-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search events, vendors, locations..." className="w-full bg-transparent outline-none"/></div><button onClick={()=>{setTab("map");searchLive(search||"event vendors")}} className="btn rounded-full px-7 py-4">Search Live</button><button onClick={()=>chooseCategory(cat)} className="primary rounded-full px-7 py-4">Create Event</button></div></div><Card><h3 className="text-2xl font-light mb-4">AI Entry Point</h3><p className="text-stone-500 mb-5">Pick a category and GatherGenius builds zones, checklists, and planning items instantly.</p><button onClick={()=>setTab("dashboard")} className="primary rounded-2xl px-5 py-3 w-full"><Sparkles className="inline h-4 w-4 mr-2"/>Start with AI</button></Card></div><h3 className="text-2xl font-light mb-4">Explore Categories</h3><div className="grid md:grid-cols-5 gap-3 mb-7">{categories.map(c=><button key={c.key} onClick={()=>chooseCategory(c.key)} className="panel rounded-[1.5rem] p-4 text-left"><p className="font-medium">{c.label}</p><p className="text-sm text-stone-500">Auto-build layout</p></button>)}</div><VendorGrid vendors={vendors} setTab={setTab}/></Section>}

{tab==="map"&&<Section icon={MapPin} title="Live Vendor Map" text="Use browser location and Google Places to find vendors near you."><div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 panel rounded-[2rem] p-4 min-h-[520px]">{process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY?<LoadScript googleMapsApiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}><GoogleMap mapContainerStyle={{width:"100%",height:"500px",borderRadius:"1.5rem"}} center={center} zoom={9}>{vendors.map((v,i)=><Marker key={i} position={{lat:Number(v.lat)||defaultCenter.lat,lng:Number(v.lng)||defaultCenter.lng}} onClick={()=>setSelected(v)}/>) }{selected&&<InfoWindow position={{lat:Number(selected.lat)||defaultCenter.lat,lng:Number(selected.lng)||defaultCenter.lng}} onCloseClick={()=>setSelected(null)}><div><strong>{selected.name}</strong><br/>{selected.category}<br/>{selected.price}</div></InfoWindow>}</GoogleMap></LoadScript>:<div className="h-[500px] rounded-[1.5rem] bg-white/70 flex flex-col items-center justify-center text-center p-8"><MapPin className="h-12 w-12 text-stone-400 mb-4"/><h3 className="text-2xl font-light">Google Map Preview</h3><p className="text-stone-500 mt-2">Add NEXT_PUBLIC_GOOGLE_MAPS_API_KEY to display the live map. Add GOOGLE_MAPS_API_KEY for live Places search.</p></div>}</div><div className="space-y-4"><Card><h3 className="text-xl font-light mb-3">Location Tools</h3><button onClick={getLocation} className="primary rounded-2xl px-4 py-3 w-full mb-3"><Navigation className="inline h-4 w-4 mr-2"/>Use My Location</button><button onClick={()=>searchLive("event vendors")} className="btn rounded-2xl px-4 py-3 w-full mb-3">Find Vendors Nearby</button><button onClick={()=>searchLive("event venues")} className="btn rounded-2xl px-4 py-3 w-full">Find Venues Nearby</button></Card>{vendors.slice(0,4).map(v=><Card key={v.name}><h4>{v.name}</h4><p className="text-stone-500 text-sm">{v.category}</p><p className="text-stone-500 text-sm mt-2"><MapPin className="inline h-4 w-4 mr-1"/>{v.location}</p><button onClick={()=>setTab("vendors")} className="primary rounded-2xl px-4 py-2 mt-4 w-full">Book</button></Card>)}</div></div></Section>}

{tab==="join"&&<Section icon={UserPlus} title="Vendor Join" text="Vendors can apply, get listed, and connect Stripe for payouts."><div className="grid lg:grid-cols-2 gap-6"><Card><h3 className="text-2xl font-light mb-4">Apply as a Vendor</h3><div className="space-y-3"><Field label="Business Name" value={vendorForm.name} set={v=>setVendorForm({...vendorForm,name:v})}/><Field label="Category" value={vendorForm.category} set={v=>setVendorForm({...vendorForm,category:v})}/><Field label="Location" value={vendorForm.location} set={v=>setVendorForm({...vendorForm,location:v})}/><Field label="Price Range" value={vendorForm.price} set={v=>setVendorForm({...vendorForm,price:v})}/><Field label="Email" value={vendorForm.email} set={v=>setVendorForm({...vendorForm,email:v})}/></div><button onClick={submitVendor} className="primary rounded-2xl px-5 py-3 mt-5 w-full">Submit Vendor Application</button></Card><Card><h3 className="text-2xl font-light mb-4">Vendor Revenue Flow</h3><ul className="space-y-3 text-stone-600"><li>• Vendor listing profile</li><li>• Featured placement option</li><li>• Stripe Connect onboarding</li><li>• Booking fee for LMH Enterprise LLC</li><li>• Reviews and verified badges</li></ul><button onClick={()=>call("/api/vendors/connect-onboard",{vendor:vendorForm,businessName})} className="btn rounded-2xl px-5 py-3 mt-5 w-full">Start Stripe Connect</button></Card></div></Section>}

{tab==="dashboard"&&<Section icon={LayoutDashboard} title="It just is." text="A warm-white command center built around presence, quiet power, and radiant clarity."><div className="grid lg:grid-cols-3 gap-6"><div className="panel rounded-[2rem] p-8 flex flex-col items-center justify-center min-h-[420px] text-center"><div className="orb mb-10"/><h2 className="text-4xl font-light tracking-[.12em] uppercase">GatherGenius</h2><p className="mt-4 text-stone-500">Constant radiant state for planning, payments, guests, vendors, and intelligence.</p></div><div className="lg:col-span-2 space-y-5"><div className="grid md:grid-cols-5 gap-4"><Metric icon={Wallet} label="Projected" value={money(total)}/><Metric icon={CreditCard} label="Collected" value={money(collected)}/><Metric icon={Users} label="RSVP" value={guests.filter(g=>g.rsvp==="Yes").length}/><Metric icon={Store} label="Vendors" value={vendors.length}/><Metric icon={CalendarDays} label="Category" value={active.label}/></div><Card><div className="grid md:grid-cols-3 gap-3"><Field label="Event Name" value={"GatherGenius Event"} set={()=>{}}/><Field label="Location" value={"Stafford, Virginia"} set={()=>{}}/><Field label="Event Date" value={"August 22, 2026"} set={()=>{}}/></div></Card><Card><h3 className="text-xl font-light mb-4">{active.label} Layout</h3><div className="grid md:grid-cols-2 gap-4"><div><p className="text-sm text-stone-500 mb-2">Suggested Zones</p>{active.zones.map(z=><div key={z} className="rounded-2xl bg-white/60 border border-stone-200 px-4 py-2 mb-2">{z}</div>)}</div><div><p className="text-sm text-stone-500 mb-2">AI Checklist</p>{active.checks.map(c=><div key={c} className="rounded-2xl bg-white/60 border border-stone-200 px-4 py-2 mb-2">{c}</div>)}</div></div></Card></div></div></Section>}

{tab==="guests"&&<Section icon={Users} title="Guests" text="RSVP, invitations, reminders, and Stripe guest payments."><p className="text-stone-500 mb-4">Split amount: <b>{money(split)}</b></p><div className="grid gap-3">{guests.map(g=><div key={g.name} className="panel rounded-[1.75rem] p-4 grid md:grid-cols-5 gap-3 items-center"><p>{g.name}</p><p>{g.rsvp}</p><p>{g.paid?"Paid":"Unpaid"}</p><button className="btn rounded-2xl px-4 py-3"><Send className="inline h-4 w-4 mr-1"/>Invite</button><button className="primary rounded-2xl px-4 py-3">Pay</button></div>)}</div></Section>}
{tab==="vendors"&&<Section icon={Store} title="Vendors" text="Book vendors and onboard them through Stripe Connect."><VendorGrid vendors={vendors} setTab={setTab}/></Section>}
{tab==="tickets"&&<Section icon={Ticket} title="Tickets" text="QR ticket check-in support."><div className="grid gap-3">{guests.map(g=><div key={g.ticket} className="panel rounded-[1.75rem] p-4 grid md:grid-cols-4 gap-3"><p>{g.name}</p><p className="font-mono"><QrCode className="inline h-4 w-4 mr-2"/>{g.ticket}</p><p>{g.paid?"Paid":"Unpaid"}</p><button className="btn rounded-2xl px-4 py-3">Scan</button></div>)}</div></Section>}
{tab==="ai"&&<Section icon={Brain} title="AI Planner" text="Connect OpenAI key for live AI planning."><Card><h3 className="text-xl font-light">Current Layout</h3><p className="text-stone-500 mt-2">{active.label}: {active.zones.join(", ")}</p></Card></Section>}
{tab==="plans"&&<Section icon={Crown} title="Plans" text="Free, Pro, and Business access layers."><div className="grid md:grid-cols-3 gap-4">{["Free $0","Pro $19/mo","Business $49/mo"].map(p=><Card key={p}><h3 className="text-2xl font-light">{p}</h3><button onClick={()=>setPlan(p.split(" ")[0].toLowerCase())} className="primary rounded-2xl px-4 py-3 mt-5 w-full">Select</button></Card>)}</div></Section>}
{tab==="redeploy"&&<Section icon={Upload} title="Redeploy" text="Deploy this live vendor + map version on Vercel."><Card><ol className="list-decimal ml-5 space-y-3 text-stone-600"><li>Use project name: <code>gathergenius-lmh</code></li><li>Add env vars from <code>.env.example</code></li><li>Add Google Maps keys</li><li>Run Supabase SQL from docs</li><li>Redeploy</li></ol></Card></Section>}
<footer className="mt-10 text-sm text-stone-500 flex justify-between gap-3 flex-wrap"><p>© 2026 GatherGenius. Payments directed to {businessName}.</p><p>{status}</p></footer>
</div></main>}
